//Install { Rest }Client Extension to use

POST http://localhost:3333/goals
Content-Type: application/json

{
  "title": "natação",
  "desiredWeeklyFrequency": 3
}

###

GET http://localhost:3333/pending-goals

###

POST http://localhost:3333/completions
Content-Type: application/json

{
  "goalId":"g8dq4mpbzwrfsdphopmsbpp0"
}

###

GET http://localhost:3333/summary